# Generated by Django 3.1.5 on 2021-07-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('who_are_we', models.TextField(max_length=1000)),
                ('mission_statement', models.TextField(max_length=1000)),
                ('vision', models.TextField(max_length=1000)),
                ('objectives', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('history', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=60)),
                ('discord_link', models.CharField(blank=True, max_length=1000)),
                ('slack_link', models.CharField(blank=True, max_length=1000)),
                ('facebook_link', models.CharField(blank=True, max_length=1000)),
                ('instagram_link', models.CharField(blank=True, max_length=1000)),
                ('twitter_link', models.CharField(blank=True, max_length=1000)),
                ('linkedin_link', models.CharField(blank=True, max_length=1000)),
                ('shared_calendar_link', models.CharField(blank=True, max_length=1000)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField()),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('url', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('clubs', models.ManyToManyField(default=None, to='clubs.Club')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.school')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('short_description', models.TextField(max_length=1000)),
                ('long_description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.school'),
        ),
    ]
