# Generated by Django 3.1.5 on 2021-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='history',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='mission_statement',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='objectives',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='vision',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='who_are_we',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
