# Generated by Django 3.1.5 on 2021-08-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210731_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField()),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(blank=True, max_length=100)),
                ('external_url', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.event')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
