# Generated by Django 3.1.5 on 2021-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20210722_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='clubs',
            field=models.ManyToManyField(blank=None, default=None, null=True, to='clubs.Club'),
        ),
    ]
