# Generated by Django 3.1.5 on 2021-08-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_resource_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.member'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.member'),
        ),
        migrations.AddField(
            model_name='update',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='year_level',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('NA', 'Not Applicable')], default='M', max_length=40),
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community_drive_url', models.CharField(blank=True, max_length=100)),
                ('repo_url', models.CharField(blank=True, max_length=100)),
                ('external_url', models.CharField(blank=True, max_length=100)),
                ('pod_lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.member')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='pod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.pod'),
        ),
    ]
