# Generated by Django 3.1.5 on 2021-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20210801_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='physical_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('G', 'Community Game'), ('LV', 'Learning Video'), ('LD', 'Learning Document'), ('D', 'Documentation'), ('U', 'Useful Resource'), ('S', 'School Resource')], max_length=150),
        ),
        migrations.AddField(
            model_name='update',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('R', 'Regular')], default='R', max_length=150),
        ),
    ]
