# Generated by Django 3.2.6 on 2021-09-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainplatform.school'),
        ),
    ]
