# Generated by Django 3.2.6 on 2021-09-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0002_alter_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainplatform.club'),
        ),
    ]
