# Generated by Django 3.2.6 on 2021-09-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0002_remove_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='event',
        ),
    ]
