# Generated by Django 3.2.6 on 2021-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0004_auto_20210903_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('HB', 'Hybrid'), ('IP', 'In-Person'), ('R', 'Remote')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
