# Generated by Django 3.2.6 on 2021-09-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0005_auto_20210903_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='time',
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(blank=True, max_length=100),
        ),
    ]
