# Generated by Django 3.2.6 on 2021-09-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0006_auto_20210903_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('TL', 'Team Lead'), ('E', 'Executive'), ('VP', 'Vice President'), ('P', 'President')], default='M', max_length=40),
        ),
        migrations.AlterField(
            model_name='update',
            name='event',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainplatform.event'),
        ),
    ]
