# Generated by Django 3.2.6 on 2021-09-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0007_auto_20210904_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_privledges', models.BooleanField(default=False)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.club')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.profile')),
            ],
        ),
    ]
