# Generated by Django 3.2.6 on 2021-09-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0008_clubrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrelationship',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.club'),
        ),
        migrations.AlterField(
            model_name='clubrelationship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.profile'),
        ),
    ]
