# Generated by Django 3.2.6 on 2021-09-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0009_auto_20210907_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubRelationship',
            new_name='ClubProfileRelationship',
        ),
    ]
