# Generated by Django 3.2.6 on 2021-09-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0010_rename_clubrelationship_clubprofilerelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='verified',
        ),
        migrations.CreateModel(
            name='ClubSchoolRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainplatform.school')),
            ],
        ),
    ]
