# Generated by Django 3.2.6 on 2021-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0011_auto_20210907_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
