# Generated by Django 3.2.6 on 2021-09-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0012_auto_20210908_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abv',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
