# Generated by Django 3.2.6 on 2021-09-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0013_club_abv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
