# Generated by Django 3.2.6 on 2021-09-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0014_auto_20210908_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='update',
            name='time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
