# Generated by Django 3.2.6 on 2021-09-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0015_auto_20210908_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='update',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(blank=True, max_length=100),
        ),
    ]
