# Generated by Django 3.2.6 on 2021-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0017_auto_20210908_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
