# Generated by Django 3.2.6 on 2021-09-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0018_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
