# Generated by Django 3.2.6 on 2021-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainplatform', '0003_auto_20211009_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
